from __future__ import annotations

import threading

from image_search_app.config import settings


class EmbeddingService:
    """Text embedding service using sentence-transformers.

    Both text queries and image captions are embedded into the same text
    vector space. For image embedding, the caller is expected to pass
    the image's caption text (generated by the captioner).
    """

    def __init__(self) -> None:
        self._model = None
        self._lock = threading.Lock()

    def _load(self) -> None:
        if self._model is not None:
            return

        with self._lock:
            # Double-check after acquiring lock
            if self._model is not None:
                return

            from sentence_transformers import SentenceTransformer

            model_name = settings.text_embedding_model_name
            try:
                model = SentenceTransformer(model_name)
            except Exception:
                model = SentenceTransformer(model_name, local_files_only=True)
            self._model = model

    def embed_text(self, text: str) -> list[float]:
        self._load()
        embedding = self._model.encode(text, convert_to_numpy=True)
        return embedding.tolist()

    def embed_image(self, image_path: str) -> list[float]:
        """Embed an image by its file path.

        Since we use a text-only embedding model, this generates a
        path-based placeholder embedding. The primary image retrieval
        path uses caption embeddings (embed_text with the BLIP caption).
        """
        self._load()
        # Use the file path as a fallback text representation
        embedding = self._model.encode(f"image: {image_path}", convert_to_numpy=True)
        return embedding.tolist()
